name: Testing

on: workflow_call

jobs:
  python:
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: "Test: Python 3.13"
            python: "3.13"
            tox-command: py313

          - name: "Test: Python 3.14"
            python: "3.14"
            tox-command: py314
            upload-coverage: true

          - name: "Typecheck: pyright"
            python: "3.14"
            tox-command: pyright

          - name: "Lint: ruff"
            python: "3.14"
            tox-command: ruff-check

          - name: "Format: ruff"
            python: "3.14"
            tox-command: ruff-format

    name: ${{ matrix.name }}
    runs-on: ubuntu-22.04
    container: ghcr.io/mopidy/ci:18
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}

      - run: python -m pip install tox

      - run: python -m tox -e ${{ matrix.tox-command }}

      - name: Upload results to Codecov
        if: ${{ matrix.upload-coverage }}
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: gbannerman/mopidy-pibox
